---
- name: Install epel repository
  yum:
    name: epel-release
    state: present

- name: Install necessary packages
  yum:
    name: "{{ guacamole_packages_EL }}"
    state: present

- name: Install CentOS-7 specific packages
  yum:
    name: "{{ centos7_packages }}"
    state: present
