---
- name: Install epel repository
  dnf:
    name: epel-release
    state: present

- name: Install RHEL specific packages
  dnf:
    name: "{{ basis_packages_EL }}"
    state: present

- name: Install MySQL Repository
  dnf:
    disable_gpg_check: yes
    name: "http://repo.mysql.com/mysql80-community-release-el{{ ansible_distribution_major_version }}.rpm"
    state: present

- name: Install GUACAMOLE specific packages
  dnf:
    name: "{{ guacamole_packages_EL }}"
    state: present

- name: ensure SELinux boolean is set for nginx reverse proxy
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: ensure SELinux boolean is set for tomcat DB connect
  seboolean:
    name: tomcat_can_network_connect_db
    state: yes
    persistent: yes
...
