---
- name: Install epel repository
  dnf:
    name: epel-release
    state: present

- name: Install iotti (Tomcat) repository
  dnf:
    disable_gpg_check: yes
    name: http://repo.iotti.biz/CentOS/8/noarch/lux-release-8-1.noarch.rpm
    state: present
    
- name: Install MySQL Repository
  dnf:
    disable_gpg_check: yes
    name: http://repo.mysql.com/mysql80-community-release-el8.rpm
    state: present 

- name: Install necessary packages
  dnf:
    name: "{{ guacamole_packages_EL }}"
    enablerepo: epel-testing
    state: present

- name: Install CentOS-8 specific packages
  dnf:
    name: "{{ centos8_packages }}"
    state: present

- name: ensure SELinux boolean is set for nginx reverse proxy
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: ensure SELinux boolean is set for tomcat DB connect
  seboolean:
    name: tomcat_can_network_connect_db
    state: yes
    persistent: yes
...
