- name: Check database schema
  shell: >
    mysql --user={{ mariadb_db_user }} \
    --password={{ mariadb_user_password }} \
    {{ mariadb_db_name }} \
    --host={{ mariadb_db_host }} \
    --execute="select * from guacamole_system_permission"
  register: check_table_exists
  failed_when: check_table_exists.stderr.find('guacamole_system_permission\' doesn\'t exist') == -1 and check_table_exists.stderr != ""
  changed_when: False

- name: Make sure guacamole-auth-jdbc-mysql is downloaded
  unarchive:
    src: 'http://apache.mirrors.tds.net/incubator/guacamole/{{ guacamole_version }}/binary/guacamole-auth-jdbc-{{ guacamole_version }}.tar.gz'
    remote_src: yes
    dest: '{{ guacamole_temp_path }}'
    creates: '{{ guacamole_temp_path }}/guacamole-auth-jdbc-{{ guacamole_version }}/mysql/guacamole-auth-jdbc-mysql-{{ guacamole_version }}.jar'
  when: check_table_exists.stderr.find('guacamole_system_permission\' doesn\'t exist') != -1

- name: Create database schema
  mysql_db:
    name: '{{ mariadb_db_name }}'
    state: import
    target: '{{ guacamole_temp_path }}/guacamole-auth-jdbc-{{ guacamole_version }}/mysql/schema/001-create-schema.sql'
  when: check_table_exists.stderr.find('guacamole_system_permission\' doesn\'t exist') != -1

- name: Create guacamole admin user
  mysql_db:
    name: '{{ mariadb_db_name }}'
    state: import
    target: '{{ guacamole_temp_path }}/guacamole-auth-jdbc-{{ guacamole_version }}/mysql/schema/002-create-admin-user.sql'
  when: check_table_exists.stderr.find('guacamole_system_permission\' doesn\'t exist') != -1

